stage: retrieve
model_ckpt_path: /data1/home/recstudio/liuqi/Nexus/benchmark/recommendation/DSSM/saves/ckpt/checkpoint-500
feature_cache_config_path: /data1/home/recstudio/liuqi/Nexus/benchmark/recommendation/DSSM/infer_data_recflow_feature_cache_config.yaml
output_topk: 1000
infer_device: 7
retrieve_index_config:
  gen_item_index: False
  item_index_path: /data1/home/recstudio/liuqi/Nexus/benchmark/recommendation/DSSM/saves/faiss_item_ivf2.index
  item_ids_path: /data1/home/recstudio/liuqi/Nexus/benchmark/recommendation/DSSM/saves/item_ids.npy
  retrieve_mode: 'u2i'
  nprobe: 10
  
  gen_i2i_index: True 
  i2i_redis_host: localhost
  i2i_redis_port: 6379
  i2i_redis_db: 4

# infer_mode: ort
infer_mode: trt
retrieval_mode: u2i
infer_batch_size: 128